version: '3'
services:
  web:
    image: nginx:latest
    expose:
      - ${XDEBUG_PORT}
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    links:
      - php
      - mysql
    depends_on:
      - mysql
  php:
    build: ./docker/php
    volumes:
      - ./:/var/www/
    working_dir: /var/www
    env_file:
      - .env.local
  mysql:
    image: mysql:8
    ports:
      - "${MYSQL_PORT}:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    env_file:
      - .env.local
